MY LEARNING ON NUMPY
* Numpy is a multi diminesional array library.
* Numpy can be used to store all kind of data like 1d,2d,3d arrays


## Why Numpy over Lists:
* Lists are slow than numpy arrays:
1-  because Numpy uses fixed types

lets say we have 5 at an array index 1,0
5->00000101
### *In Numpy:*
  -Int32=> 00000000 00000000 00000000 00000101 (*memory space of 4 bytes*)(by default)
  -Int16=> 00000000 00000101 *or*
  -Int08=> 00000101

## *In Lists*
  -uses built in int type in python
  -int type built contains many information:
    1> Size: of integer value
    2> Reference Count: how many the integer is being specifically pointed at
    3> Object Type
    4> Object Value

  -Hence Representation:
     00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000101 (*memory size 8 bytes*)


2-Faster to read less bytes of memory
3-In numpy array we dont have to do type checking each time
4-numpy utilizes contigous memory allocation scheme
   Benefit:
    * *CPUs have SIMD(Single Instruction Multiple Data) Vector Processing Unit beacuse of this we can perform computation of all the values at one time*
    * *Effective Cache Utilization*




## Application of Numpy-
   * MATLAB Replacement
   * Plotting
   * Backend
   * Machine Learning
   

In [2]:
import numpy as np

### The Basics

In [3]:
#Integer array
a=np.array([1,2,3], dtype='int16')
print(a)

#Float Array
b=np.array([[1.3,4.3,2.2],[6.0,7.6,5.6]])
print(b)

[1 2 3]
[[1.3 4.3 2.2]
 [6.  7.6 5.6]]


In [4]:
#Get Dimensions
a.ndim

#Get Shape
b.shape

#Get Type
a.dtype

#Get ItemSize
a.itemsize

#Get total size
a.nbytes

6

## Acessing/Changing specific elements, rows, columns, etc

In [5]:
a= np.array([[1,2,3,4,5,6],[8,9,1,2,3,4]])
print(a)

[[1 2 3 4 5 6]
 [8 9 1 2 3 4]]


In [6]:
#Get a specific element [r,c]
print(a[1,5])   # //4
print(a[1,-1])  # //4

4
4


In [7]:
#Get a specific row
print(a[0,:])

#Get a specific column
print(a[:,2])

[1 2 3 4 5 6]
[3 1]


In [8]:
#[startindex:endindex:stepssize]
print(a[0,1:6:2])    
print(a[0,1:6:-2])
print(a[0,1:-1:2])

[2 4 6]
[]
[2 4]


In [9]:
#Assinging and Changing elements values
a[1,5]=20
print(a)


#Changing entire column
a[:,2]=5
print(a)

#Specified changes
a[:,2]=[1,3]
print(a)

[[ 1  2  3  4  5  6]
 [ 8  9  1  2  3 20]]
[[ 1  2  5  4  5  6]
 [ 8  9  5  2  3 20]]
[[ 1  2  1  4  5  6]
 [ 8  9  3  2  3 20]]


In [10]:
#3-D Example
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)


#Get Specified element
print(b[0,1,1])

#Get columns
print(b[:,1,:])

#Replace
b[:,1,:]= [9,9]

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
4
[[3 4]]


## Initializing different types of Arrays

In [11]:
#All Zeros Matrix
np.zeros(5)
np.zeros((2,3))
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [12]:
#All Ones Matrix
np.ones((4,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [13]:
#Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [14]:
#Any other number full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [15]:
# Random numbers
np.random.rand(4,2)

#If want to pass shape
np.random.random_sample(a.shape)

array([[0.31837985, 0.38601986, 0.43621765, 0.94281157, 0.93611736,
        0.21421073],
       [0.71475274, 0.68614163, 0.68977047, 0.86914504, 0.49878017,
        0.44232387]])

The *randint()* function takes two parameters: low and high. 
These parameters specify the range of integers that can be generated. 
In the example you provided, only high parameter is specified as 7, which means that the function will generate a random integer between 0 and 6 inclusive. 
The number 7 is excluded from the range because the function generates integers up to, but not including, the value of high.

In [16]:
#Random Integer Values

np.random.randint(7)    


5

*randint(7, size=(3, 3))* is a function that generates random integers between 0 and 6 (inclusive) and arranges them into a 3x3 array. The first argument (7) specifies the upper bound (exclusive) for the random integers, and the second argument (size=(3, 3)) specifies the shape of the array.

In [25]:
np.random.randint(1,7,size=(3,3))  #1-lower limit #7-higher limit
np.random.randint(-3,5,size=(2,3))

array([[ 2,  0,  0],
       [ 3, -1,  2]])

#

In [26]:
#The Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#Repeat Array elements
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [32]:
#Repeating 2D Array/Vector
arr=np.array([[1,2,3],[4,5,6]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [36]:
output = np.ones([5,5])
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z    #[1:-1,1:-1]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
a=np.array([1,2,3])
b=a                       #We just told be do whatever b does we didn't copied it
b[0]=100
print(a)

#Now a will also have 100 at it's 0th index
#To Overcome this

[100   2   3]


In [43]:
#copy function
a=np.array([1,2,3])
b=a.copy()                   
b[0]=100
print(a)

[1 2 3]


### Mathematics 

In [44]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [52]:
#Element wise a+k/a-k
a+2  #Addition
a-3  #Subtraction
a*2   #Multiplication
a/2   #Division
a**2   #Power


a+=2
print(a)

[ 7  8  9 10]


In [51]:
b=np.array([1,0,1,0])
a+b

array([6, 6, 8, 8])

In [53]:
#Take the sin
np.sin(a)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

## Linear Algebra

In [56]:
a=np.ones((2,3))
b=np.full((3,2),2)
#3 columns of a is equal to 3 rows of b
#Matrix Multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [57]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)
#An Identity Matrix has determinant of 1

1.0

#### Statistics

In [58]:
stats= np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
#Finding Min & Max
np.min(stats)
np.max(stats)
#Finding min/max along any axis
np.min(stats,axis=1)
np.min(stats,axis=0)

array([1, 2, 3, 4])

In [62]:
#Finding Sum all of ele in matrix
np.sum(stats)

36

#### Reorganizing Arrays

In [66]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [69]:
#We want to make this before array of 2,4 shape as 8,1
#We get errors when values dont fit in vs the original shape
after= before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [74]:
#Vertically stacking vectors/matrixs
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [75]:
#Horizontal stacking vectors/matrixs
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])

#### Files

In [ ]:
#Load Data from Files
filedata= np.genfromtxt('data.txt',delimiter=',')
#delimiter is the sperator used in file(data.txt)
#Data will be printed in float type hence,
#genfromtxt will handle alll the new lines of files

filedata.astype('int32')
filedata

#### Boolean Masking & Advanced Indexing

In [ ]:
filedata > 50       #gives true/false depending on the values of file data
filedata>=50
filedata[filedata>50]   #will only give you values that are greater than 50


In [76]:
#You can index with a list in Numpy
a=np.array([1,2,3,4,56,6,78,8])
a[[1,2,3]]

array([2, 3, 4])

In [ ]:
#Checking for any value >50 in columns
np.any(filedata>50, axis=0)
np.all(filedata>50,axis=0)

In [ ]:
((filedata>50) & (filedata<100))
(~((filedata>50)) & (filedata<100))

1 2 3 4 5
6 7 8 9 10
11 12 13 14 15
16 17 18 19 20
21 22 23 24 25
26 27 28 29 30
#Consider this array

In [ ]:
#Acessing 11 12 16 17
a[2:4,0:2]

#Acessing 2,8,14,20
a[[0,1,2,3],[1,2,3,4]]

#Acessing 4,5,24,25,29,30
a[[0,4,5],[3:]] #3 onwards